services: 
  postgress:
    image: postgres:15
    container_name: rust-todo-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '35432:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data